import AuthProvider from '-/context/auth-provider';
import { ThemeProvider } from '-/context/theme-provider';
import TRPCProvider from '-/trpc/provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Intellektuelle Schule 2023',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='id'>
      <body className={inter.className}>
        <AuthProvider>
          <TRPCProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='dark'
            >
              {children}
            </ThemeProvider>
          </TRPCProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
